// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5W4Vz8bcHfkI80NM7QfjxVwZIn5qSn4',
    appId: '1:90329613211:web:9f332a98e421e53aef573e',
    messagingSenderId: '90329613211',
    projectId: 'chat-app-4c395',
    authDomain: 'chat-app-4c395.firebaseapp.com',
    storageBucket: 'chat-app-4c395.appspot.com',
    measurementId: 'G-8KVVTM9TQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZwXuczJv1zAq5MYvKYNkGkDeWC5b9fXE',
    appId: '1:90329613211:android:5ca3a6bd77ce4c98ef573e',
    messagingSenderId: '90329613211',
    projectId: 'chat-app-4c395',
    storageBucket: 'chat-app-4c395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlFRlw_2tcdu9Eq__i0Y6BCjgngO_TLqI',
    appId: '1:90329613211:ios:0d959de8b0fb8fc8ef573e',
    messagingSenderId: '90329613211',
    projectId: 'chat-app-4c395',
    storageBucket: 'chat-app-4c395.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
